import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { buildUrl } from "cloudinary-build-url";
import imageGallery from "../data/images";
import { AdvancedImage } from "@cloudinary/react";
import { Cloudinary } from "@cloudinary/url-gen";
import LargeImage from "../components/largeImage";

export default function Home() {


  const categories = {
    bedroom: "bedroom",
    kitchen: "kitchen",
    bathroom: "bath",
    livingroom: "living",
    diningroom: "diningroom",
    outside: "outside"
  };
  // 3. Get your image
  //===================

  // Instantiate a CloudinaryImage object for the image with the public ID, 'docs/models'.
  // https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653300086/OIB/IMG_0834_yb8wls.jpg
  // https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653300086/OIB/IMG_0838_c8ypkj.jpg
  return (
    <div className={styles.container}>
      <Head>
        <title>Anchor Inn at OIB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to The Anchor Inn at Ocean Isle Beach</h1>
        <section>

<p>

The Anchor Inn is located on the west side of Ocean Isle Beach. The house has 5 bedrooms and 5 1/2 baths. Each bedroom has its own bath.  Each bedroom has a 32” TV.
</p>
<p>
The house is a reverse house plan, in which, the kitchen is located on the upper floor for the best views. There are 3 bedrooms located on the lower floor with 2 bedrooms located on the upper floor. Also, on the lower floor is the laundry room and a wet bar.
</p>

<p>
With rental of the house your family will have access to the community pool that is located at 101 West Ocean Drive.
It is a short 3-5 minute walk from the house. Also, with your rental, your family will have access to the elevator, beach chairs, linens and bath towels.
</p>
<p>
After coming in from the beach the house offers a spacious outdoor shower with hot and cold water with a huge dressing area.
</p>


        </section>


          {/* <CloudinaryImages images={imageGallery} /> */}
          <h2>Outside</h2>
          <div className={styles.grid}>

          <LargeImage imagePage={imageGallery} category={categories.outside} />
          <LargeImage imagePage={imageGallery} category="outside-shower" />

          </div>

          <h2>Kitchen</h2>
          <div className={styles.grid}>

          <LargeImage imagePage={imageGallery} category={categories.kitchen} />

          </div>


          <h2>Bedrooms</h2>
          <div className={styles.grid}>

          <LargeImage imagePage={imageGallery} category={categories.bedroom} />

          </div>

          <h2>Living areas</h2>
          <div className={styles.grid}>

          <LargeImage imagePage={imageGallery} category={categories.livingroom} />

          </div>

          <h2>Bathrooms</h2>
          <div className={styles.grid}>

          <LargeImage imagePage={imageGallery} category={categories.bathroom} />

          </div>
          <h2>Video Tours</h2>

          <div className={styles.grid}>

          <div className={styles.card}>
            <Link href="https://res.cloudinary.com/lwd-loganwebdev/video/upload/v1653300111/OIB/IMG_6613_rfd68q.mov">
              <Image
                src={
                  "https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653991034/OIB/Screen_Shot_2022-05-31_at_5.56.58_AM_dfghy1.png"
                }
                alt="Galaxy"
                height={2138}
                width={1222}
              />
            </Link>
          </div>

          <div className={styles.card}>
            <Link href="https://res.cloudinary.com/lwd-loganwebdev/video/upload/v1653485088/OIB/1080lowq_cf2myk.mp4">
              <Image
                src={
                  "https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653990869/OIB/Screen_Shot_2022-05-31_at_5.53.46_AM_wbjcw2.png"
                }
                alt="Galaxy"
                height={2142}
                width={1216}
              />
            </Link>
          </div>

          <div className={styles.card}>
            <Link href="https://res.cloudinary.com/lwd-loganwebdev/video/upload/v1653300109/OIB/IMG_6614_hkwwg9.mov">
              <Image
                src={
                  "https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653991171/OIB/Screen_Shot_2022-05-31_at_5.59.16_AM_nprcml.png"
                }
                alt="Galaxy"
                height={2142}
                width={1216}
              />
            </Link>
          </div>


          </div>


      </main>

      <footer className={styles.footer}>

          <Link
            href="https://www.loganwebdev.com"
            target="_blank"
            rel="noopener noreferrer"
          >Powered by Logan Web Dev</Link>

      </footer>
    </div>
  );
}
