import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { buildUrl } from 'cloudinary-build-url';
import imageGallery from '../data/images';
import {AdvancedImage} from '@cloudinary/react';
import {Cloudinary} from "@cloudinary/url-gen";
import LargeImage from '../components/largeImage';

export default function Home() {



  // 3. Get your image
  //===================

  // Instantiate a CloudinaryImage object for the image with the public ID, 'docs/models'.
// https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653300086/OIB/IMG_0834_yb8wls.jpg
// https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653300086/OIB/IMG_0838_c8ypkj.jpg
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
Welcome to the beach!
        </h1>
      <p>Take a look around. Click on each image/video to view full size. </p>

        <div className={styles.grid}>
          {/* <CloudinaryImages images={imageGallery} /> */}
    <LargeImage imagePage={imageGallery} />

    <div className={styles.card}>
    <Link href='https://res.cloudinary.com/lwd-loganwebdev/video/upload/v1653300111/OIB/IMG_6613_rfd68q.mov'>

                <Image
                  src={'https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653318639/OIB/Screen_Shot_2022-05-23_at_11.10.05_AM_nhnbeo.png'}
                  alt="Galaxy"
                  height={2138}
                  width={1222}
                />

          </Link>



    </div>

    <div className={styles.card}>
    <Link href='https://res.cloudinary.com/lwd-loganwebdev/video/upload/v1653300109/OIB/IMG_6614_hkwwg9.mov'>

                <Image
                  src={'https://res.cloudinary.com/lwd-loganwebdev/image/upload/v1653318924/OIB/Screen_Shot_2022-05-23_at_11.14.24_AM_xfkxju.png'}
                  alt="Galaxy"
                  height={2142}
                  width={1216}
                />

          </Link>



    </div>

          </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
